### ISSUE TITLE
Testing the 'test-app'

### ISSUE THREAD

**Issue by hrandika** [zzOzz/minikube-gitlab-tutorial#1]
Can you provide more information how test the running test application written in Java?

**Comment by zzOzz** [comment]
Take a look at the [Makefile](https://github.com/zzOzz/minikube-gitlab-tutorial/blob/master/Makefile#L32)
replace the test-app-golang folder by the test-app-java at step 06
you can change the app version manually
[here](https://github.com/zzOzz/minikube-gitlab-tutorial/blob/master/test-app-java/pom.xml#L7)
and repush your repo.

**Comment by hrandika** [comment]
Can we see the ruining test app in Kubernetes cluster? 
http://helloworld:8080/ Gives ERR_CONNECTION_REFUSED
Services and ingress are created.Pods are deployed as well.

**Comment by zzOzz** [comment]
the default port for ingress is 80 (and 443 for SSL) so you can view your app

[http://helloworld.local](http://helloworld.local)
