### ISSUE TITLE
Invalid Login or password. gitlab

### ISSUE THREAD

**Issue by wandelson** [zzOzz/minikube-gitlab-tutorial#3]
Hello,

What are the access credentials?

root
UtM-5ov-2um-5Ho

did not work..

=/

**Comment by wandelsonlb** [comment]
and http://gitlab/


This site can’t be reached gitlab’s server IP address could not be found.

**Comment by zzOzz** [comment]
You have to add the hostname in your /etc/hosts file 
#add this Line
127.0.0.1 gitlab
